Support LLVM 11
viktormalik/diffkemp pull request #184
Opened 2021-03-16 10:42 UTC by viktormalik

A number of changes was required:
- `StringRef` is not implicitly casted to `std::string` (needs `.str()` call)
- `CallInst::getCalledValue` was replaced by `CallInst::getCalledOperand`
- `SequentialType` was replaced by `ArrayType`
- custom `AnalysisManager` needs to include `<llvm/IR/PassManagerImpl.h>`
- some functions have changed headers (`CallInst::Create`, `InlineFunction`)
- `AttributeList` does not have context field
- `CallInst::getParamAlignment` was replaced by `CallInst::getParamAlign`

The container image is updated with LLVM 11 and Python 3.8 (as Ubuntu 16.04 contains Python 3.6 which has a bug in pip).

2021-03-21 19:45 UTC, PSilling requested changes
Other than the minor cosmetic changes, I do not see any issues. Since all tests passed, I would say that the PR is in a very good shape.

2021-03-21 19:45 UTC, PSilling commented on diffkemp/simpll/Utils.cpp
> +/// Handles situation then the actual function is inside a bitcast or alias.
Typo: should probably be `Handles situations when`.

2021-03-21 19:45 UTC, PSilling commented on diffkemp/simpll/Utils.cpp
> +    auto *fun = dyn_cast<Function>(Value);
I believe that `Fun` would be better here, since other variable names are also capitalized.

2021-03-22 10:13 UTC, PSilling approved these changes

2021-03-22 12:47 UTC, tmalecova approved these changes

2021-03-22 12:48 UTC, merged