Save LLVM version when running diffkemp generate
viktormalik/diffkemp pull request #220
Opened 2022-03-07 14:50 UTC by zacikpa

This PR resolves #199.

When running `diffkemp generate`, saves the current LLVM **major** version into the snapshot YAML file.
When running `diffkemp compare`, checks whether the major version in use now is the same as in both snapshots. If not, fails.

There is no need to check for minor version differences, as [minor versions are never released](http://blog.llvm.org/2016/12/llvms-new-versioning-scheme.html). Furthermore, different patch versions should be compatible, so they are not checked either.

2022-03-08 06:03 UTC, viktormalik requested changes

2022-03-08 06:03 UTC, viktormalik commented on diffkemp/diffkemp.py
> +            "Error: old snapshot uses LLVM {}, current is {}.\n".format(
```suggestion
            "Error: old snapshot was built with LLVM {}, current is {}.\n".format(
```
Same below.

2022-03-08 20:41 UTC, zacikpa commented on diffkemp/diffkemp.py
> +            "Error: old snapshot uses LLVM {}, current is {}.\n".format(
Fixed.

2022-03-14 09:30 UTC, viktormalik approved these changes
Can you squash the commits, please?

2022-03-14 12:39 UTC, merged