Handle comparison of relocated code
viktormalik/diffkemp pull request #233
Opened 2022-06-23 09:54 UTC by viktormalik

A common refactoring is when a piece of code is moved into another part of the function (e.g. from inside the loop before the loop head). This helps to compare such a change as semantically equal.

Handling code relocations is done in 3 phases, they roughly correspond to states of the new enum `RelocationInfo::Status`.
- Relocation detection is run when a difference is found and no relocation has been found so far (status is `None`). Detection is done by trying to "skip" a block of code in one of the basic blocks and match the remaining parts of the blocks. If it succeeds, the relocation is stored.
- Relocation matching is run when a difference is found and there is a previously found potential relocation (state is `Stored`). In such a case, we reset the current instruction iterator to the head of the stored relocation (in the appropriate program) and continue the comparison (state is changed to `Matching`). Once all relocation instructions were successfully compared, the state is reset to `None` and the last phase is run.
- Relocation checking checks if the relocated code has no dependency on the skipped code. Direct data dependencies are resolved by the SSA property of LLVM IR, so this only checks indirect dependencies through load/store instructions. This is simply done by checking if both the relocated and the skipped code access the same pointer and one of the accesses is a write. In such a case, the relocation is evaluated as not equal.

See commit messages for more implementation details.

Note that relocation detection must be run after all other approaches to show equality (including custom pattern matching) are tried.

2022-07-03 21:56 UTC, PSilling requested changes
Great quality code. The only issue I have is that it ignores the recently introduced `mappedValuesBySn` map (necessary for custom pattern matching).

2022-07-03 21:56 UTC, PSilling commented on diffkemp/simpll/DifferentialFunctionComparator.cpp
> +                sn_mapL.erase(&*InstL);
Maybe replace by a call to `DifferentialFunctionComparator::undoLastInstCompare`?

2022-07-03 21:56 UTC, PSilling commented on diffkemp/simpll/DifferentialFunctionComparator.cpp
> +    sn_mapL.erase(&*InstL);
`DifferentialFunctionComparator::undoLastInstCompare` again.

2022-07-03 21:56 UTC, PSilling commented on diffkemp/simpll/DifferentialFunctionComparator.cpp
> +        auto sn_mapL_backup = sn_mapL;
`mappedValuesBySn` should get backed up as well since `cmpValues` (i.e., `cmpOperationsWithOperands`) may change it as well.

2022-07-20 09:47 UTC, viktormalik commented
> Great quality code. The only issue I have is that it ignores the recently introduced `mappedValuesBySn` map (necessary for custom pattern matching).

Good point, thanks. Should be fixed now.

2022-08-04 12:53 UTC, PSilling approved these changes
Indeed, looks great!

2022-08-25 06:02 UTC, merged